version: "3.7"

networks:
  net-alice-kms:
  net-alice:
  net-bob:
  net-public:

services:

  val-alice:
    command: start
    container_name: val-alice
    image: runos_chaind_i
    networks:
      - net-alice-kms
      - net-alice
    volumes:
      - ./docker/val-alice:/root/.runos_chain

  sentry-alice:
    command: start
    container_name: sentry-alice
    image: runos_chaind_i
    networks:
      - net-alice
      - net-public
    volumes:
      - ./docker/sentry-alice:/root/.runos_chain

  val-bob:
    command: start
    container_name: val-bob
    image: runos_chaind_i
    networks:
      - net-bob
    volumes:
      - ./docker/val-bob:/root/.runos_chain

  sentry-bob:
    command: start
    container_name: sentry-bob
    image: runos_chaind_i
    networks:
      - net-bob
      - net-public
    volumes:
      - ./docker/sentry-bob:/root/.runos_chain

  node-carol:
    command: start
    container_name: node-carol
    image: runos_chaind_i
    networks:
      - net-public
    ports:
      - 0.0.0.0:26657:26657
    volumes:
      - ./docker/node-carol:/root/.runos_chain
