// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSetPort } from "./types/runoschain/configstore/tx";
import { MsgCreateHostsDatabase } from "./types/runoschain/configstore/tx";
import { MsgUpdateHostsDatabase } from "./types/runoschain/configstore/tx";
import { MsgDeleteHostsDatabase } from "./types/runoschain/configstore/tx";


export { MsgSetPort, MsgCreateHostsDatabase, MsgUpdateHostsDatabase, MsgDeleteHostsDatabase };

type sendMsgSetPortParams = {
  value: MsgSetPort,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateHostsDatabaseParams = {
  value: MsgCreateHostsDatabase,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateHostsDatabaseParams = {
  value: MsgUpdateHostsDatabase,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteHostsDatabaseParams = {
  value: MsgDeleteHostsDatabase,
  fee?: StdFee,
  memo?: string
};


type msgSetPortParams = {
  value: MsgSetPort,
};

type msgCreateHostsDatabaseParams = {
  value: MsgCreateHostsDatabase,
};

type msgUpdateHostsDatabaseParams = {
  value: MsgUpdateHostsDatabase,
};

type msgDeleteHostsDatabaseParams = {
  value: MsgDeleteHostsDatabase,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSetPort({ value, fee, memo }: sendMsgSetPortParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSetPort: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSetPort({ value: MsgSetPort.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSetPort: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateHostsDatabase({ value, fee, memo }: sendMsgCreateHostsDatabaseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateHostsDatabase: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateHostsDatabase({ value: MsgCreateHostsDatabase.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateHostsDatabase: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateHostsDatabase({ value, fee, memo }: sendMsgUpdateHostsDatabaseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateHostsDatabase: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateHostsDatabase({ value: MsgUpdateHostsDatabase.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateHostsDatabase: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteHostsDatabase({ value, fee, memo }: sendMsgDeleteHostsDatabaseParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteHostsDatabase: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteHostsDatabase({ value: MsgDeleteHostsDatabase.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteHostsDatabase: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSetPort({ value }: msgSetPortParams): EncodeObject {
			try {
				return { typeUrl: "/runos_chain.configstore.MsgSetPort", value: MsgSetPort.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSetPort: Could not create message: ' + e.message)
			}
		},
		
		msgCreateHostsDatabase({ value }: msgCreateHostsDatabaseParams): EncodeObject {
			try {
				return { typeUrl: "/runos_chain.configstore.MsgCreateHostsDatabase", value: MsgCreateHostsDatabase.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateHostsDatabase: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateHostsDatabase({ value }: msgUpdateHostsDatabaseParams): EncodeObject {
			try {
				return { typeUrl: "/runos_chain.configstore.MsgUpdateHostsDatabase", value: MsgUpdateHostsDatabase.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateHostsDatabase: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteHostsDatabase({ value }: msgDeleteHostsDatabaseParams): EncodeObject {
			try {
				return { typeUrl: "/runos_chain.configstore.MsgDeleteHostsDatabase", value: MsgDeleteHostsDatabase.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteHostsDatabase: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			RunosChainConfigstore: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;