// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: runoschain/configstore/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetHostsDatabaseRequest struct {
	Dpid string `protobuf:"bytes,1,opt,name=dpid,proto3" json:"dpid,omitempty"`
	Mac  string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *QueryGetHostsDatabaseRequest) Reset()         { *m = QueryGetHostsDatabaseRequest{} }
func (m *QueryGetHostsDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetHostsDatabaseRequest) ProtoMessage()    {}
func (*QueryGetHostsDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{2}
}
func (m *QueryGetHostsDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHostsDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHostsDatabaseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHostsDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHostsDatabaseRequest.Merge(m, src)
}
func (m *QueryGetHostsDatabaseRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHostsDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHostsDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHostsDatabaseRequest proto.InternalMessageInfo

func (m *QueryGetHostsDatabaseRequest) GetDpid() string {
	if m != nil {
		return m.Dpid
	}
	return ""
}

func (m *QueryGetHostsDatabaseRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type QueryGetHostsDatabaseResponse struct {
	HostsDatabase HostsDatabase `protobuf:"bytes,1,opt,name=hostsDatabase,proto3" json:"hostsDatabase"`
}

func (m *QueryGetHostsDatabaseResponse) Reset()         { *m = QueryGetHostsDatabaseResponse{} }
func (m *QueryGetHostsDatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetHostsDatabaseResponse) ProtoMessage()    {}
func (*QueryGetHostsDatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{3}
}
func (m *QueryGetHostsDatabaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetHostsDatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetHostsDatabaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetHostsDatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetHostsDatabaseResponse.Merge(m, src)
}
func (m *QueryGetHostsDatabaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetHostsDatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetHostsDatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetHostsDatabaseResponse proto.InternalMessageInfo

func (m *QueryGetHostsDatabaseResponse) GetHostsDatabase() HostsDatabase {
	if m != nil {
		return m.HostsDatabase
	}
	return HostsDatabase{}
}

type QueryAllHostsDatabaseRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHostsDatabaseRequest) Reset()         { *m = QueryAllHostsDatabaseRequest{} }
func (m *QueryAllHostsDatabaseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllHostsDatabaseRequest) ProtoMessage()    {}
func (*QueryAllHostsDatabaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{4}
}
func (m *QueryAllHostsDatabaseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHostsDatabaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHostsDatabaseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHostsDatabaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHostsDatabaseRequest.Merge(m, src)
}
func (m *QueryAllHostsDatabaseRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHostsDatabaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHostsDatabaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHostsDatabaseRequest proto.InternalMessageInfo

func (m *QueryAllHostsDatabaseRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllHostsDatabaseResponse struct {
	HostsDatabase []HostsDatabase     `protobuf:"bytes,1,rep,name=hostsDatabase,proto3" json:"hostsDatabase"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllHostsDatabaseResponse) Reset()         { *m = QueryAllHostsDatabaseResponse{} }
func (m *QueryAllHostsDatabaseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllHostsDatabaseResponse) ProtoMessage()    {}
func (*QueryAllHostsDatabaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{5}
}
func (m *QueryAllHostsDatabaseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllHostsDatabaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllHostsDatabaseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllHostsDatabaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllHostsDatabaseResponse.Merge(m, src)
}
func (m *QueryAllHostsDatabaseResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllHostsDatabaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllHostsDatabaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllHostsDatabaseResponse proto.InternalMessageInfo

func (m *QueryAllHostsDatabaseResponse) GetHostsDatabase() []HostsDatabase {
	if m != nil {
		return m.HostsDatabase
	}
	return nil
}

func (m *QueryAllHostsDatabaseResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPortRequest struct {
	Dpid string `protobuf:"bytes,1,opt,name=dpid,proto3" json:"dpid,omitempty"`
	Mac  string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
}

func (m *QueryGetPortRequest) Reset()         { *m = QueryGetPortRequest{} }
func (m *QueryGetPortRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPortRequest) ProtoMessage()    {}
func (*QueryGetPortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{6}
}
func (m *QueryGetPortRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPortRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPortRequest.Merge(m, src)
}
func (m *QueryGetPortRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPortRequest proto.InternalMessageInfo

func (m *QueryGetPortRequest) GetDpid() string {
	if m != nil {
		return m.Dpid
	}
	return ""
}

func (m *QueryGetPortRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type QueryGetPortResponse struct {
	Inport string `protobuf:"bytes,1,opt,name=inport,proto3" json:"inport,omitempty"`
}

func (m *QueryGetPortResponse) Reset()         { *m = QueryGetPortResponse{} }
func (m *QueryGetPortResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPortResponse) ProtoMessage()    {}
func (*QueryGetPortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401d0ae7c9201751, []int{7}
}
func (m *QueryGetPortResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPortResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPortResponse.Merge(m, src)
}
func (m *QueryGetPortResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPortResponse proto.InternalMessageInfo

func (m *QueryGetPortResponse) GetInport() string {
	if m != nil {
		return m.Inport
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "runos_chain.configstore.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "runos_chain.configstore.QueryParamsResponse")
	proto.RegisterType((*QueryGetHostsDatabaseRequest)(nil), "runos_chain.configstore.QueryGetHostsDatabaseRequest")
	proto.RegisterType((*QueryGetHostsDatabaseResponse)(nil), "runos_chain.configstore.QueryGetHostsDatabaseResponse")
	proto.RegisterType((*QueryAllHostsDatabaseRequest)(nil), "runos_chain.configstore.QueryAllHostsDatabaseRequest")
	proto.RegisterType((*QueryAllHostsDatabaseResponse)(nil), "runos_chain.configstore.QueryAllHostsDatabaseResponse")
	proto.RegisterType((*QueryGetPortRequest)(nil), "runos_chain.configstore.QueryGetPortRequest")
	proto.RegisterType((*QueryGetPortResponse)(nil), "runos_chain.configstore.QueryGetPortResponse")
}

func init() {
	proto.RegisterFile("runoschain/configstore/query.proto", fileDescriptor_401d0ae7c9201751)
}

var fileDescriptor_401d0ae7c9201751 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0x69, 0x1b, 0x71, 0xa4, 0x50, 0xc6, 0xa0, 0x25, 0xd4, 0x8d, 0xae, 0x60, 0xd4,
	0xd6, 0x1d, 0x5b, 0x35, 0x20, 0xea, 0xa1, 0xa5, 0x18, 0x8f, 0x31, 0x78, 0xf2, 0x12, 0x26, 0x9b,
	0xe9, 0x66, 0x61, 0xb3, 0xb3, 0xdd, 0x99, 0x88, 0xa5, 0xf4, 0xe2, 0xd9, 0x83, 0xe0, 0xdd, 0x2f,
	0xe0, 0xcd, 0x73, 0x3f, 0x40, 0x8f, 0x05, 0x2f, 0x9e, 0x44, 0x12, 0x3f, 0x88, 0xec, 0xec, 0x5b,
	0xdd, 0xa1, 0x1d, 0x93, 0xd2, 0xdb, 0xec, 0xee, 0xf3, 0x3e, 0xef, 0xef, 0xfd, 0x33, 0x8b, 0xdd,
	0x74, 0x14, 0x0b, 0xe9, 0x0f, 0x58, 0x18, 0x53, 0x5f, 0xc4, 0x3b, 0x61, 0x20, 0x95, 0x48, 0x39,
	0xdd, 0x1d, 0xf1, 0x74, 0xcf, 0x4b, 0x52, 0xa1, 0x04, 0xb9, 0xae, 0x35, 0x5d, 0x2d, 0xf2, 0x0a,
	0xa2, 0x5a, 0x35, 0x10, 0x81, 0xd0, 0x1a, 0x9a, 0x9d, 0x72, 0x79, 0x6d, 0x25, 0x10, 0x22, 0x88,
	0x38, 0x65, 0x49, 0x48, 0x59, 0x1c, 0x0b, 0xc5, 0x54, 0x28, 0x62, 0x09, 0x5f, 0xef, 0xfb, 0x42,
	0x0e, 0x85, 0xa4, 0x3d, 0x26, 0x21, 0x0b, 0x7d, 0xb7, 0xde, 0xe3, 0x8a, 0xad, 0xd3, 0x84, 0x05,
	0x61, 0xac, 0xc5, 0xa0, 0xbd, 0x6d, 0x81, 0x4b, 0x58, 0xca, 0x86, 0x27, 0x86, 0xab, 0x16, 0xd1,
	0x40, 0x48, 0x25, 0xbb, 0x7d, 0xa6, 0x58, 0x96, 0x2a, 0x17, 0xbb, 0x55, 0x4c, 0x5e, 0x67, 0x39,
	0xdb, 0xda, 0xa1, 0xc3, 0x77, 0x47, 0x5c, 0x2a, 0xf7, 0x0d, 0xbe, 0x6a, 0xbc, 0x95, 0x89, 0x88,
	0x25, 0x27, 0x2f, 0x70, 0x25, 0xcf, 0xb4, 0x8c, 0x6e, 0xa2, 0xbb, 0x57, 0x36, 0xea, 0x9e, 0xa5,
	0x11, 0x5e, 0x1e, 0xb8, 0x35, 0x7f, 0xf4, 0xb3, 0x5e, 0xea, 0x40, 0x90, 0xbb, 0x8d, 0x57, 0xb4,
	0x6b, 0x8b, 0xab, 0x57, 0x19, 0xcb, 0x36, 0xa0, 0x40, 0x56, 0x42, 0xf0, 0x7c, 0x3f, 0x09, 0xfb,
	0xda, 0xfc, 0x72, 0x47, 0x9f, 0xc9, 0x12, 0x9e, 0x1b, 0x32, 0x7f, 0xb9, 0xac, 0x5f, 0x65, 0x47,
	0x57, 0xe2, 0x1b, 0x16, 0x17, 0xa0, 0xec, 0xe0, 0xc5, 0x41, 0xf1, 0x03, 0xc0, 0xde, 0xb1, 0xc2,
	0x1a, 0x36, 0xc0, 0x6c, 0x5a, 0xb8, 0x3b, 0x80, 0xbe, 0x19, 0x45, 0x67, 0xa2, 0xbf, 0xc4, 0xf8,
	0xdf, 0xb0, 0xfe, 0x26, 0xcc, 0x27, 0xeb, 0xe9, 0x76, 0xe7, 0xfb, 0x03, 0x93, 0xf5, 0xda, 0x2c,
	0x38, 0x89, 0xed, 0x14, 0x22, 0xdd, 0x43, 0x04, 0xd5, 0x9d, 0x4e, 0x64, 0xaf, 0x6e, 0xee, 0x82,
	0xd5, 0x91, 0x96, 0x41, 0x5f, 0xd6, 0xf4, 0x8d, 0xa9, 0xf4, 0x39, 0x90, 0x81, 0xff, 0x0c, 0xf6,
	0xa6, 0xc5, 0x55, 0x5b, 0xa4, 0xea, 0x7c, 0x83, 0xf5, 0x70, 0xd5, 0x0c, 0x86, 0x8a, 0xaf, 0xe1,
	0x4a, 0x18, 0x27, 0x22, 0x55, 0x10, 0x0f, 0x4f, 0x1b, 0x5f, 0x17, 0xf0, 0x82, 0x0e, 0x20, 0x1f,
	0x11, 0xae, 0xe4, 0x1b, 0x47, 0x56, 0xad, 0x7d, 0x38, 0xbd, 0xe6, 0xb5, 0xb5, 0xd9, 0xc4, 0x39,
	0x87, 0xdb, 0xf8, 0xf0, 0xfd, 0xf7, 0xe7, 0xf2, 0x2d, 0x52, 0xa7, 0x85, 0xa8, 0x33, 0xae, 0x21,
	0x39, 0x44, 0x78, 0xd1, 0xe8, 0x3a, 0x79, 0xf2, 0xff, 0x44, 0x96, 0x0b, 0x51, 0x6b, 0x9e, 0x37,
	0x0c, 0x48, 0x9f, 0x6b, 0xd2, 0x26, 0x79, 0x6c, 0x25, 0x35, 0xff, 0x05, 0x74, 0x3f, 0x1b, 0xc9,
	0x01, 0xdd, 0x1f, 0x32, 0xff, 0x80, 0x7c, 0x43, 0x78, 0xc9, 0xf0, 0xdd, 0x8c, 0xa2, 0x69, 0x15,
	0x58, 0xee, 0xc5, 0xb4, 0x0a, 0x6c, 0x5b, 0xee, 0x52, 0x5d, 0xc1, 0x3d, 0xd2, 0x98, 0xb1, 0x02,
	0xf2, 0x05, 0xe1, 0x4b, 0xb0, 0x38, 0x64, 0x6d, 0x6a, 0xdb, 0x0a, 0xcb, 0x59, 0x7b, 0x30, 0xa3,
	0x1a, 0xc8, 0x9a, 0x9a, 0xec, 0x21, 0xf1, 0xac, 0x64, 0x01, 0x57, 0xdd, 0x6c, 0x41, 0x8d, 0xae,
	0x6e, 0x3d, 0x3d, 0x1a, 0x3b, 0xe8, 0x78, 0xec, 0xa0, 0x5f, 0x63, 0x07, 0x7d, 0x9a, 0x38, 0xa5,
	0xe3, 0x89, 0x53, 0xfa, 0x31, 0x71, 0x4a, 0x6f, 0xeb, 0x45, 0xa3, 0xf7, 0x86, 0x95, 0xda, 0x4b,
	0xb8, 0xec, 0x55, 0xf4, 0xaf, 0xfa, 0xd1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x24, 0xec,
	0xd4, 0x9b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a HostsDatabase by index.
	HostsDatabase(ctx context.Context, in *QueryGetHostsDatabaseRequest, opts ...grpc.CallOption) (*QueryGetHostsDatabaseResponse, error)
	// Queries a list of HostsDatabase items.
	HostsDatabaseAll(ctx context.Context, in *QueryAllHostsDatabaseRequest, opts ...grpc.CallOption) (*QueryAllHostsDatabaseResponse, error)
	// Queries a list of GetPort items.
	GetPort(ctx context.Context, in *QueryGetPortRequest, opts ...grpc.CallOption) (*QueryGetPortResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/runos_chain.configstore.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HostsDatabase(ctx context.Context, in *QueryGetHostsDatabaseRequest, opts ...grpc.CallOption) (*QueryGetHostsDatabaseResponse, error) {
	out := new(QueryGetHostsDatabaseResponse)
	err := c.cc.Invoke(ctx, "/runos_chain.configstore.Query/HostsDatabase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HostsDatabaseAll(ctx context.Context, in *QueryAllHostsDatabaseRequest, opts ...grpc.CallOption) (*QueryAllHostsDatabaseResponse, error) {
	out := new(QueryAllHostsDatabaseResponse)
	err := c.cc.Invoke(ctx, "/runos_chain.configstore.Query/HostsDatabaseAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPort(ctx context.Context, in *QueryGetPortRequest, opts ...grpc.CallOption) (*QueryGetPortResponse, error) {
	out := new(QueryGetPortResponse)
	err := c.cc.Invoke(ctx, "/runos_chain.configstore.Query/GetPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a HostsDatabase by index.
	HostsDatabase(context.Context, *QueryGetHostsDatabaseRequest) (*QueryGetHostsDatabaseResponse, error)
	// Queries a list of HostsDatabase items.
	HostsDatabaseAll(context.Context, *QueryAllHostsDatabaseRequest) (*QueryAllHostsDatabaseResponse, error)
	// Queries a list of GetPort items.
	GetPort(context.Context, *QueryGetPortRequest) (*QueryGetPortResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) HostsDatabase(ctx context.Context, req *QueryGetHostsDatabaseRequest) (*QueryGetHostsDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostsDatabase not implemented")
}
func (*UnimplementedQueryServer) HostsDatabaseAll(ctx context.Context, req *QueryAllHostsDatabaseRequest) (*QueryAllHostsDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HostsDatabaseAll not implemented")
}
func (*UnimplementedQueryServer) GetPort(ctx context.Context, req *QueryGetPortRequest) (*QueryGetPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPort not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runos_chain.configstore.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HostsDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetHostsDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HostsDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runos_chain.configstore.Query/HostsDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HostsDatabase(ctx, req.(*QueryGetHostsDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HostsDatabaseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllHostsDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HostsDatabaseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runos_chain.configstore.Query/HostsDatabaseAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HostsDatabaseAll(ctx, req.(*QueryAllHostsDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/runos_chain.configstore.Query/GetPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPort(ctx, req.(*QueryGetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "runos_chain.configstore.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "HostsDatabase",
			Handler:    _Query_HostsDatabase_Handler,
		},
		{
			MethodName: "HostsDatabaseAll",
			Handler:    _Query_HostsDatabaseAll_Handler,
		},
		{
			MethodName: "GetPort",
			Handler:    _Query_GetPort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runoschain/configstore/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetHostsDatabaseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHostsDatabaseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHostsDatabaseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mac) > 0 {
		i -= len(m.Mac)
		copy(dAtA[i:], m.Mac)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Mac)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Dpid) > 0 {
		i -= len(m.Dpid)
		copy(dAtA[i:], m.Dpid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Dpid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetHostsDatabaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetHostsDatabaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetHostsDatabaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.HostsDatabase.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllHostsDatabaseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHostsDatabaseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHostsDatabaseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllHostsDatabaseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllHostsDatabaseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllHostsDatabaseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.HostsDatabase) > 0 {
		for iNdEx := len(m.HostsDatabase) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HostsDatabase[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPortRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPortRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPortRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mac) > 0 {
		i -= len(m.Mac)
		copy(dAtA[i:], m.Mac)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Mac)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Dpid) > 0 {
		i -= len(m.Dpid)
		copy(dAtA[i:], m.Dpid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Dpid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPortResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPortResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPortResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Inport) > 0 {
		i -= len(m.Inport)
		copy(dAtA[i:], m.Inport)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Inport)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetHostsDatabaseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Dpid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Mac)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetHostsDatabaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.HostsDatabase.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllHostsDatabaseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllHostsDatabaseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.HostsDatabase) > 0 {
		for _, e := range m.HostsDatabase {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPortRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Dpid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Mac)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPortResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Inport)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHostsDatabaseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHostsDatabaseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHostsDatabaseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dpid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dpid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetHostsDatabaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetHostsDatabaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetHostsDatabaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostsDatabase", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HostsDatabase.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHostsDatabaseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHostsDatabaseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHostsDatabaseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllHostsDatabaseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllHostsDatabaseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllHostsDatabaseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostsDatabase", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostsDatabase = append(m.HostsDatabase, HostsDatabase{})
			if err := m.HostsDatabase[len(m.HostsDatabase)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPortRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPortRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPortRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dpid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dpid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPortResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPortResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPortResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
